type: object
description: Successful process replacement response
properties:
  status:
    type: string
    enum:
      - success
  message:
    type: string
    description: Success message indicating process was replaced
  processId:
    type: string
    description: ID of the replaced process
  processSummary:
    $ref: 'bblocks://ogc.api.processes.v2.schemas.processSummaryDRU'
  links:
    type: array
    items:
      $ref: 'bblocks://ogc.api.processes.v1.schemas.link'
required:
  - status
  - processId
  - processSummary
