description: the process being added is already deployed (i.e. duplicate)
content:
  application/json:
    schema:
      $ref: bblocks://ogc.api.processes.v1.schemas.exception
  text/html:
    schema:
      type: string
